In [ ]:
##-----------------------------------------------
##-----------------------------------------------
## 6 kyu
## Convert integer to Whitespace format# Unique In Order
## inicio (2022-10-10)
## DONE   (2022-10-10)
##
##-----------------------------------------------
##-----------------------------------------------

In [237]:
def whitespace_number(n):
    
    fc = ' '
    if n == 0:
        out = fc + '\n'
        return out
        #return  out.replace(' ', '[space]').replace('\\t', '[tab]').replace('\\n', '[LF]')
    
    else:
        tmp = format(n, "b")
        if tmp [0] == '-':
            fc = '\t'
        mc = ''

    
        for l in tmp:
            if l == '0':
                mc = mc + ' '
            if l == '1':
                mc = mc + '\t'
      
        out = fc + mc + '\n'
        return out
        #return out.replace(' ', '[space]').replace('\\t', '[tab]').replace('\\n', '[LF]')

In [238]:
print (whitespace_number(1))
# " \t\n"

In [226]:
print (whitespace_number(0))
# " \n"

 \n


In [227]:
print (whitespace_number(-1))
# "\t\t\n"

\t\t\n


In [228]:
print (whitespace_number(2))
# " \t \n"

 \t \n


In [229]:
print (whitespace_number(-3))
# "\t\t\t\n"

\t\t\t\n


In [230]:
print (whitespace_number(-21))
# "\t\t\t\n"

\t\t \t \t\n


In [ ]:
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
## 6 kyu
## Unique In Order
## inicio (2022-10-10)
## DONE   (2022-10-10)
##
##-----------------------------------------------
##-----------------------------------------------

In [126]:
def est_subsets(arr):
    
    def factorial(n):
        if n == 0 or n == 1:
            return 1
        else:
            return n*factorial(n-1)
        pass

    Unique = list(set(arr))
    m = len (Unique)
    
    f1 = factorial (m)
    s = 0
    
    for n in range (m):
        s += (f1 // ((factorial (n) * factorial (m-n)))) 
    
    return int(s)

In [127]:
arr = [1, 2, 3, 4]
print (est_subsets(arr))
#15

15


In [128]:
arr = ['a', 'b', 'c', 'd', 'd']
print (est_subsets(arr))
#15

15


In [129]:
arr = [2, 3, 4, 5, 5, 6, 6, 7, 8, 8]
print (est_subsets(arr))
#127

127


In [130]:
arr = ['a', 'z', 'z', 'z', 'b', 'j', 'f', 'k', 'b', 'd', 'j', 'j', 'n', 'm', 'm']
print (est_subsets(arr))
#511

511


In [121]:
arr = [1] * 8
print (est_subsets(arr))
#1

1


In [125]:
arr = []
print (est_subsets(arr))
#0

0


In [ ]:
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
## 6 kyu
## Unique In Order
## inicio (2022-10-10)
## DONE   (2022-10-10)
##
##-----------------------------------------------
##-----------------------------------------------

In [101]:
def unique_in_order(iterable):
    
    out2 = []
    
    if len (iterable) > 0:
        out = str(iterable[0])
        a = str(iterable[0])
    
        for l in iterable:
            if a != str(l):
                out += str(l)
                a = str(l)
        
        if type(iterable[0]).__name__ == 'int':
            out2 = list(map(int,out))
        else:
            out2 = list(out)
    return out2


In [102]:
print (unique_in_order('AAAABBBCCDAABBB'))
#['A', 'B', 'C', 'D', 'A', 'B']       

['A', 'B', 'C', 'D', 'A', 'B']


In [103]:
print (unique_in_order('ABBCcAD'))
#['A', 'B', 'C', 'c', 'A', 'D'] 

['A', 'B', 'C', 'c', 'A', 'D']


In [104]:
print (unique_in_order([1,2,2,3,3]))
#[1,2,3]

[1, 2, 3]


In [ ]:
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
## 6 kyu
## Decode the Morse code
## inicio (2022-10-10)
## DONE   (2022-10-10)
##
##-----------------------------------------------
##-----------------------------------------------

In [65]:
def decode_morse(morse_code):
    # ToDo: Accept dots, dashes and spaces, return human-readable message
    MorseCode_D = {'SOS':'...---...', 'A':'.-',  'B':'-...', 'C':'-.-.', 'D':'-..',  'E':'.',    'F':'..-.',
                   'G':'--.', 'H':'....', 'I':'..',   'J':'.---', 'K':'-.-',  'L':'.-..',
                   'M':'--',  'N':'-.',   'O':'---',  'P':'.--.', 'Q':'--.-', 'R':'.-.',
                   'S':'...', 'T':'-',    'U':'..-',  'V':'...-', 'W':'.--',  'X':'-..-', 'Y':'-.--', 'Z':'--..',
                   '1':'.----', '2':'..---', '3':'...--', '4':'....-', '5':'.....', '6':'-....',
                   '7':'--...', '8':'---..', '9':'----.', '0':'-----',
                   ', ':'--..--', '.':'.-.-.-', '?':'..--..', '/':'-..-.', '-':'-....-', '(':'-.--.', ')':'-.--.-',
                   '!':'-.-.--'}
    
  
    morse_code = morse_code.strip ()
    morse_code += ' '
    print (morse_code)
    dtxt = ''
    ctmp = ''
    
    for l in morse_code:
        #print (l)
        if (l != ' '):             # checks for space
            v = 0                  # counter to keep track of space
            ctmp += l              # storing morse code of a single character
 
        else:                      # in case of space
            v += 1                 # if v = 1 that indicates a new character
            if v == 1:
                # accessing the keys using their values (reverse of encryption)
                #print ('v:',v,' ctmp:', ctmp)
                dtxt += list(MorseCode_D.keys())[list(MorseCode_D.values()).index(ctmp)]
                #print ('v:', v, ' ctmp:', ctmp,' dtxt:',dtxt)
                ctmp = ''
            if v == 3 :            # if v = 2 that indicates a new word
                dtxt += ' '        # adding space to separate words
    return dtxt
    
    
    #return morse_code.replace('.', MORSE_CODE['.']).replace('-', MORSE_CODE['-']).replace(' ', '')

In [66]:
print (decode_morse('.... . -.--   .--- ..- -.. .'))
# HEY JUDE

.... . -.--   .--- ..- -.. . 
HEY JUDE


In [67]:
print (decode_morse('...---...'))
# SOS

...---... 
SOS


In [68]:
print (decode_morse(' . '))
# E

. 
E


In [69]:
print (decode_morse('   .   . '))
# E

.   . 
E E


In [70]:
print (decode_morse('      ...---... -.-.--   - .... .   --.- ..- .. -.-. -.-   -... .-. --- .-- -.   ..-. --- -..-   .--- ..- -- .--. ...   --- ...- . .-.   - .... .   .-.. .- --.. -.--   -.. --- --. .-.-.-  '))
# 'SOS! THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.')

...---... -.-.--   - .... .   --.- ..- .. -.-. -.-   -... .-. --- .-- -.   ..-. --- -..-   .--- ..- -- .--. ...   --- ...- . .-.   - .... .   .-.. .- --.. -.--   -.. --- --. .-.-.- 
SOS! THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.


In [45]:
###===================================================================
### https://www.geeksforgeeks.org/morse-code-translator-python/
###===================================================================
def decrypt(message):
 
    # extra space added at the end to access the last morse code
    message += ' '
    decipher = ''
    citext = ''
    
    for letter in message:
         # checks for space
        if (letter != ' '):
            # counter to keep track of space
            i = 0
 
            # storing morse code of a single character
            citext += letter
 
        # in case of space
        else:
            # if i = 1 that indicates a new character
            i += 1
 
            # if i = 2 that indicates a new word
            if i == 2 :
 
                 # adding space to separate words
                decipher += ' '
            else:
 
                # accessing the keys using their values (reverse of encryption)
                decipher += list(MORSE_CODE_DICT.keys())[list(MORSE_CODE_DICT
                .values()).index(citext)]
                citext = ''
 
    return decipher

In [ ]:

 
# Function to encrypt the string
# according to the morse code chart
def encrypt(message):
    
    MorseCode_D = { 'A':'.-', 'B':'-...', 'C':'-.-.', 'D':'-..', 'E':'.', 'F':'..-.',
                'G':'--.', 'H':'....', 'I':'..', 'J':'.---', 'K':'-.-', 'L':'.-..',
                'M':'--', 'N':'-.', 'O':'---', 'P':'.--.', 'Q':'--.-', 'R':'.-.',
                'S':'...', 'T':'-', 'U':'..-', 'V':'...-', 'W':'.--', 'X':'-..-', 'Y':'-.--', 'Z':'--..',
                '1':'.----', '2':'..---', '3':'...--', '4':'....-', '5':'.....', '6':'-....',
                '7':'--...', '8':'---..', '9':'----.', '0':'-----',
                ', ':'--..--', '.':'.-.-.-', '?':'..--..', '/':'-..-.', '-':'-....-', '(':'-.--.', ')':'-.--.-'}
    cipher = ''
    for letter in message:
        if letter != ' ':
 
            # Looks up the dictionary and adds the
            # corresponding morse code
            # along with a space to separate
            # morse codes for different characters
            cipher += MorseCode_D[letter] + ' '
        else:
            # 1 space indicates different characters
            # and 2 indicates different words
            cipher += ' '
 
    return cipher

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
## 6 kyu
## Take a Ten Minutes Walk
## inicio (2022-09-30)
## DONE   (2022-09-30)
##
##-----------------------------------------------
##-----------------------------------------------

In [ ]:
def is_valid_walk(walk):
    #determine if walk is valid
    
    x = 0
    y = 0
    
    for w in walk:
        print (w,x,y)
        match w:
            case 'n': x = x+1
            case 's': x = x-1 
            case 'e': y = y+1 
            case 'w': y = y-1 
        
    
    if (len(walk) == 10) and (x == 0 and y == 0):
        return True
    else :
        return False
    pass

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------

In [1]:
##-----------------------------------------------
##-----------------------------------------------
## 6 kyu
## ASCII Sierpiński Carpet
## inicio (2022-09-22)
## DONE   (2022-09-22)
##
## https://www.youtube.com/watch?v=-k3AK02JQlI
## https://en.wikipedia.org/wiki/Sierpi%C5%84ski_carpet
##-----------------------------------------------
##-----------------------------------------------

In [23]:
def sierpinski_carpet_string(n):    
    mk = ["██"]
    cont = 1
    while cont <= n:
        m1 = [3*b for b in mk]
        mk = m1 + [b+b.replace("█", " ") + b for b in mk] + m1
        cont += 1
    return ("\n".join(mk))

In [24]:
print (sierpinski_carpet_string(3))

██████████████████████████████████████████████████████
██  ████  ████  ████  ████  ████  ████  ████  ████  ██
██████████████████████████████████████████████████████
██████      ████████████      ████████████      ██████
██  ██      ██  ████  ██      ██  ████  ██      ██  ██
██████      ████████████      ████████████      ██████
██████████████████████████████████████████████████████
██  ████  ████  ████  ████  ████  ████  ████  ████  ██
██████████████████████████████████████████████████████
██████████████████                  ██████████████████
██  ████  ████  ██                  ██  ████  ████  ██
██████████████████                  ██████████████████
██████      ██████                  ██████      ██████
██  ██      ██  ██                  ██  ██      ██  ██
██████      ██████                  ██████      ██████
██████████████████                  ██████████████████
██  ████  ████  ██                  ██  ████  ████  ██
██████████████████                  ██████████████████
██████████

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
## 6 kyu
## Framed Reflection
## inicio (2022-09-22)
## DONE   (2022-09-22)
##-----------------------------------------------
##-----------------------------------------------

In [29]:
def mirror(text):
    
    def freverse(x):
        rx = x[::-1]
        return rx
    
    
    nl = text.split()
    mx = 0
    ltr = []
    ltrf = []
    
    for n in nl:
        lg = len(n) 
        if lg > mx:
            mx = lg
        ltr.append (freverse(n))
    
    for tr in ltr:
        sz = len(tr)
        if sz < mx:
            ltrf.append ("* " + tr + " " * (mx-sz) + " *\n")
        else:
            ltrf.append("* " + tr + " *\n") 
    
        
    tx1 = "**" + "*" * mx + "**\n"
    tx2 = ''.join(map(str,ltrf))
    tx3 =  "**" + "*" * mx + "**"
    
    return (tx1 + tx2 + tx3)

In [30]:
print (mirror("Hello World"))

*********
* olleH *
* dlroW *
*********


In [31]:
print (mirror("emosewA !ataK"))

***********
* Awesome *
* Kata!   *
***********


In [ ]:
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
## 6 kyu
## Find the missing letter
## inicio (2022-09-20)
## DONE   (2022-09-20)
##-----------------------------------------------
##-----------------------------------------------

In [54]:
def find_missing_letter(chars):
    
    rf = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
    flg = 0
    
    #if chars is "upper case" then transform to "lower case"
    if chars[0].isupper():
        flg = 1
        c = list(map(str.lower,chars))
    else:
        c = chars
    
    subrf = rf[rf.index(c[0]):rf.index(c[len(chars)-1]) +1]
    out = list(set(c) ^ set(subrf))
    
    if flg == 1:
        out = list(map(str.upper,out))

    return out[0]

In [55]:
print(find_missing_letter(['a','b','c','d','f']))
print(find_missing_letter(['O','Q','R','S']))

e
P


In [ ]:
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
## 6 kyu
## Who likes it?
## inicio (2022-08-18)
## DONE   (2022-08-18)
##-----------------------------------------------
##-----------------------------------------------

In [8]:
def likes(names):
    # your code here
    txt01 = 'no one'
    txtR1 = ' likes this'
    txtR2 = ' like this'
    l = len (names)
    
    match l:
        case 0: out = txt01 + txtR1
        case 1: out = names[0] + txtR1
        case 2: out = names[0] + ' and ' + names [1] + txtR2
        case 3: out = names[0] + ', ' + names [1] + ' and ' + names [2] + txtR2
        case other:  out = names[0] + ', ' + names [1] +  ' and ' + str(l-2) + ' others' + txtR2
        
    return out  
    pass

SyntaxError: invalid syntax (<ipython-input-8-b760aec82229>, line 8)

In [6]:
print (likes([]))

NameError: name 'likes' is not defined

In [ ]:
print (likes(['Peter']))

In [ ]:
print (likes(['Jacob', 'Alex']))

In [ ]:
print (likes(['Max', 'John', 'Mark']))

In [ ]:
print (likes(['Alex', 'Jacob', 'Mark', 'Max']))

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
## 6 kyu
## How many pages in a book?
## inicio (2022-08-16)
## DONE   (2022-08-16)
##-----------------------------------------------
##-----------------------------------------------

In [19]:
def amount_of_pages(summary):
    if summary == 0:
        return None
    
    else:
        val = 0
        #l = list(range(1, summary + 1))
        
        for i in range (1, summary+1):
            val = len(str(i)) + val
            #print (val)
            if val == summary:
                return i

In [20]:
print (amount_of_pages(25))

1
2
3
4
5
6
7
8
9
11
13
15
17
19
21
23
25
17


In [ ]:
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
## 6 kyu
## Simple number triangle
## inicio (2022-08-16)
## DONE   (2022-08-18)
##-----------------------------------------------
##-----------------------------------------------

In [87]:
# l0 = np.zeros(n, dtype=np.float64)
# a = np.array(dtype=np.int64)
# a = np.zeros(shape=(n,n), dtype=np.int64)
# a.astype(float)
# a = np.arange(n,n, dtype=np.float64) 
# b = np.int64 (sum (a[n-1,:]))

In [ ]:
## n = 1   # 1 0  0   0    0    0     0      0     0     0       sum = 1
## n = 2   # 1 1  0   0    0    0     0      0     0     0       sum = 2   
## n = 3   # 1 2  2   0    0    0     0      0     0     0       sum = 5
## n = 4   # 1 3  5   5    0    0     0      0     0     0       sum = 14
## n = 5   # 1 4  9   14   14   0     0      0     0     0       sum = 42
## n = 6   # 1 5  14  28   42   42    0      0     0     0       sum = 132
## n = 7   # 1 6  20  48   90   132   132    0     0     0       sum = 429
## n = 8   # 1 7  27  75   165  297   429    429   0     0       sum = 1430
## n = 9   # 1 8  35  110  275  572   1001   1430  1430  0       sum = 4862 
## n = 10  # 1 9  44  154  429  1001  2002   3432  4862  4862    sum = 16796


In [385]:
# https://en.wikipedia.org/wiki/Catalan_number
## RESUELTO OK
# Catalan_number
# The first Catalan numbers for n = 0, 1, 2, 3, ... are
# 1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862, 16796, 58786

def solve(n):
    
    def factorial(f):
        if f == 0 or f == 1:
            return 1
        else:
            return f*factorial(f-1)
    
    a = factorial (2*(n))
    b = factorial (n)
    C = a // ((b**2)*(n+1))    # if you use / instead // float error appears 
    #print ('a: ', a, 'b: ', b, 'C: ', C)
    
    return C
    pass

In [386]:
print('para n=5 ;',solve (5))
print('para n=6 ;',solve (6))
print('para n=8 ;',solve (8))
print('para n=10 ;',solve (10))
print('para n=1000; ', solve (1000))

para n=5 ; 42
para n=6 ; 132
para n=8 ; 1430
para n=10 ; 16796
para n=1000;  2046105521468021692642519982997827217179245642339057975844538099572176010191891863964968026156453752449015750569428595097318163634370154637380666882886375203359653243390929717431080443509007504772912973142253209352126946839844796747697638537600100637918819326569730982083021538057087711176285777909275869648636874856805956580057673173655666887003493944650164153396910927037406301799052584663611016897272893305532116292143271037140718751625839812072682464343153792956281748582435751481498598087586998603921577523657477775758899987954012641033870640665444651660246024318184109046864244732001962029120


In [358]:
## funciona en CODEWARS pero da ERROR por el tiempo que consume
import numpy as np
def solve(n):
    l0 = [0] * n
    l1 = [0] * n
    l0 [0] = 1
    l1 [0] = 1
    c = 1
    
    while c <= n:
        for i in range (1, c):
            l1[i] =  np.long (l1[i-1]) + np.long (l0[i])
        print (l1)
        l0 = list (l1)
        l1 = [0] * n
        l1 [0] = 1
        c = c +1
    return np.long(sum (l0))
    pass

In [359]:
print('para n=5 ;',solve (5))
print('para n=6 ;',solve (6))
print('para n=8 ;',solve (8))
print('para n=10 ;',solve (8))
print('para n=1000; ', solve (1000))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [332]:
## solve   (falla para numeros grandes)
import numpy as np

def solve(n):
    a = numpy.zeros(shape=(n,n))
    #a = np.zeros(shape=(n,n), dtype=np.long)
    a[:,0] = 1
    
    for i in range (1, n):
        for j in range (1, i+1):
            #a[i,j] =  np.long (a[i-1,j] + a[i,j-1])                         ## RuntimeWarning: overflow encountered in double_scalars
            a[i][j] = np.long (a[i-1][j] + a[i][j-1])                     ## RuntimeWarning: overflow encountered in double_scalars
            #a[i][j] = np.long (a[i-1][j]) + np.long (a[i][j-1])            ## OverflowError: int too large to convert to float 
            #a[i][j] = np.long (np.long (a[i-1][j]) + np.long (a[i][j-1]))
    
    print (a)
    b = sum (a[n-1,:])
    b = np.long (sum (a[n-1,:]))
    
    return b
    pass

In [336]:
print('para n=5 ;',solve (5))
print('para n=8 ;',solve (8))
print('para n=1000; ', solve (1000))

[[ 1.  0.  0.  0.  0.]
 [ 1.  1.  0.  0.  0.]
 [ 1.  2.  2.  0.  0.]
 [ 1.  3.  5.  5.  0.]
 [ 1.  4.  9. 14. 14.]]
para n=5 ; 42
[[  1.   0.   0.   0.   0.   0.   0.   0.]
 [  1.   1.   0.   0.   0.   0.   0.   0.]
 [  1.   2.   2.   0.   0.   0.   0.   0.]
 [  1.   3.   5.   5.   0.   0.   0.   0.]
 [  1.   4.   9.  14.  14.   0.   0.   0.]
 [  1.   5.  14.  28.  42.  42.   0.   0.]
 [  1.   6.  20.  48.  90. 132. 132.   0.]
 [  1.   7.  27.  75. 165. 297. 429. 429.]]
para n=8 ; 1430


<ipython-input-332-97e4859eaae9>:12: RuntimeWarning: overflow encountered in double_scalars
  a[i][j] = np.long (a[i-1][j] + a[i][j-1])                     ## RuntimeWarning: overflow encountered in double_scalars


OverflowError: cannot convert float infinity to integer

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
## 6 kyu
## Ranking NBA teams
## inicio 
## DONE   
##-----------------------------------------------
##-----------------------------------------------

In [ ]:
r = ("Los Angeles Clippers 104 Dallas Mavericks 88,New York Knicks 101 Atlanta Hawks 112,Indiana Pacers 103 Memphis Grizzlies 112,"
     "Los Angeles Lakers 111 Minnesota Timberwolves 112,Phoenix Suns 95 Dallas Mavericks 111,Portland Trail Blazers 112 New Orleans Pelicans 94,"
     "Sacramento Kings 104 Los Angeles Clippers 111,Houston Rockets 85 Denver Nuggets 105,Memphis Grizzlies 76 Cleveland Cavaliers 106,"
     "Milwaukee Bucks 97 New York Knicks 122,Oklahoma City Thunder 112 San Antonio Spurs 106,Boston Celtics 112 Philadelphia 76ers 95,"
     "Brooklyn Nets 100 Chicago Bulls 115,Detroit Pistons 92 Utah Jazz 87,Miami Heat 104 Charlotte Hornets 94,"
     "Toronto Raptors 106 Indiana Pacers 99,Orlando Magic 87 Washington Wizards 88,Golden State Warriors 111 New Orleans Pelicans 95,"
     "Atlanta Hawks 94 Detroit Pistons 106,Chicago Bulls 97 Cleveland Cavaliers 95,"
     "San Antonio Spurs 111 Houston Rockets 86,Chicago Bulls 103 Dallas Mavericks 102,Minnesota Timberwolves 112 Milwaukee Bucks 108,"
     "New Orleans Pelicans 93 Miami Heat 90,Boston Celtics 81 Philadelphia 76ers 65,Detroit Pistons 115 Atlanta Hawks 87,"
     "Toronto Raptors 92 Washington Wizards 82,Orlando Magic 86 Memphis Grizzlies 76,Los Angeles Clippers 115 Portland Trail Blazers 109,"
     "Los Angeles Lakers 97 Golden State Warriors 136,Utah Jazz 98 Denver Nuggets 78,Boston Celtics 99 New York Knicks 85,"
     "Indiana Pacers 98 Charlotte Hornets 86,Dallas Mavericks 87 Phoenix Suns 99,Atlanta Hawks 81 Memphis Grizzlies 82,"
     "Miami Heat 110 Washington Wizards 105,Detroit Pistons 94 Charlotte Hornets 99,Orlando Magic 110 New Orleans Pelicans 107,"
     "Los Angeles Clippers 130 Golden State Warriors 95,Utah Jazz 102 Oklahoma City Thunder 113,San Antonio Spurs 84 Phoenix Suns 104,"
     "Chicago Bulls 103 Indiana Pacers 94,Milwaukee Bucks 106 Minnesota Timberwolves 88,Los Angeles Lakers 104 Portland Trail Blazers 102,"
     "Houston Rockets 120 New Orleans Pelicans 100,Boston Celtics 111 Brooklyn Nets 105,Charlotte Hornets 94 Chicago Bulls 86,"
     "Cleveland Cavaliers 103 Dallas Mavericks 97,New York Knicks 101.12 Atlanta Hawks 112")


In [ ]:
def nba_cup(result_sheet, to_find):
    
    teams = ("Los Angeles Clippers,Dallas Mavericks,New York Knicks,NYK,Atlanta Hawks,Indiana Pacers,Memphis Grizzlies,"
         "Los Angeles Lakers,Minnesota Timberwolves,Phoenix Suns,Portland Trail Blazers,New Orleans Pelicans,"
         "Sacramento Kings,Los Angeles Clippers,Houston Rockets,Denver Nuggets,Cleveland Cavaliers,Milwaukee Bucks,"
         "Oklahoma City Thunder,San Antonio Spurs,Boston Celtics,Philadelphia 76ers,Brooklyn Nets,Chicago Bulls,"
         "Detroit Pistons,Utah Jazz,Miami Heat,Charlotte Hornets,Toronto Raptors,Orlando Magic,Washington Wizards,"
         "Golden State Warriors,Dallas Maver") 
    
    teams_list = teams.split(",")
    if to_find in teams_list:
        
        #localiza el equipo
        r_list = result_sheet.split(",")
        chk = [x for x in r_list if to_find in x]
        #print (chk)
         
        mtrx = []
        
        #identifica los numeros
        for chk_item in chk:
            #print (chk_item)
            #numbers = [float(temp) for temp in chk_item.split() if temp.isdigit()]
            numbers = [int(temp) for temp in chk_item.split() if temp.isdigit()]
            #print(numbers)
            #a = numbers[0]
            #b = numbers[1]
            #print (len(numbers))
            
            if len(numbers) <= 1:
                output = "Error(float number):" + chk_item
                return (output)
            
            else:
                pos = chk_item.find(to_find)
                l = []
                
                a = int (numbers[0])
                b = int (numbers[1])
                
                if pos == 0:
                    l.append (a)
                    l.append (b)
                else:
                    l.append (b)
                    l.append (a)
                    
                if l[0] > l[1]:   #win
                    l.append (1)
                    l.append (0)
                    l.append (0)
            
                if l[0] < l[1]:   #loss
                    l.append (0)
                    l.append (1)
                    l.append (0)
                
                if l[0] == l[1]:  #draw
                    l.append (0)
                    l.append (0)
                    l.append (1)
            
            mtrx.append(l)
            #print (mtrx)
        
        o1 = 0     #scored
        o2 = 0     #conceded 
        o3 = 0     #W
        o4 = 0     #L
        o5 = 0     #D
        o6 = 0     #points
        
        for x in range (len(mtrx)):
            o1 = o1 + mtrx [x][0]
            o2 = o2 + mtrx [x][1]
            o3 = o3 + mtrx [x][2]
            o4 = o4 + mtrx [x][3]
            o5 = o5 + mtrx [x][4]
        o6 = o6 + o3 * 3 + o5 
        
        #print (o1, o2, o3, o4, o5)
        output = to_find + ':W=' + str(o3) + ';D=' + str(o5) + ';L=' + str(o4) + ';Scored=' + str(o1) +';Conceded=' + str(o2) + ';Points=' + str(o6)

    else:
        if to_find == '':
            output = ''
        else:
            output = to_find + ":This team didn't play!"
        return (output)
    
    return (output)

In [ ]:
nba_cup(r, "Boston Celt")

In [ ]:
nba_cup(r, "Los Angeles Clippers")

In [ ]:
nba_cup(r, "Boston Celtics")

In [ ]:
nba_cup(r, "New York Knicks")

In [ ]:
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------
##-----------------------------------------------